data_cfg:
  dataset_name: Gait3D-Parsing
  dataset_root: Gait3D-pars-64-64-pkl
  dataset_partition: datasets/Gait3D/Gait3D.json
  num_workers: 4
  remove_no_gallery: false # Remove probe if no gallery for it
  test_dataset_name: Gait3D-Parsing

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: true
  restore_hint: 180000
  save_name: MTSGait
  eval_func: evaluate_Gait3D
  metric: cos # cos euc
  sampler:
    batch_shuffle: false
    batch_size: 8
    sample_type: all_ordered # all indicates whole sequence used to test, while ordered means input sequence by its natural order; Other options:   fixed_unordered
    frames_all_limit: 720 # limit the number of sampled frames to prevent out of memory
  transform:
    - type: BaseParsingCuttingTransform

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 0.1
    scale: 16
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true

model_cfg:
  model: MTSGait
  backbone_cfg:
    in_channels: 1
    layers_cfg: # Layers configuration for automatically model construction
      - BC-64
      - BCMTSRES-64
      - M
      - BCMTSRES-128
      - BCMTSRES-128
      - M
      - BCMTSRES-256
      - BCMTSRES-256
      # - M
      # - BCMTSRES-512
      # - BCMTSRES-512
    type: PlainMTS
    n_segment: 30   # equal to trainer_cfg.sampler.frames_num_fixed
    n_div: 16   # shift_div = (1 / n_div) * 2
    # start_iter: 50001   # start iteration for shiftting
    skip_times:
      - 1
      - 3
    shift_type: bi_direction   # uni_direction / bi_direction
  SeparateFCs:
    in_channels: 256
    out_channels: 256
    parts_num: 31
  SeparateBNNecks:
    class_num: 3000
    in_channels: 256
    parts_num: 31
  bin_num:
    - 16
    - 8
    - 4
    - 2
    - 1

optimizer_cfg:
  lr: 0.001
  momentum: 0.9
  solver: Adam
  weight_decay: 0.0005

scheduler_cfg:
  gamma: 0.1
  milestones: # Learning Rate Reduction at each milestones
    - 30000
    - 90000
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true # half_percesion float for memory reduction and speedup
  fix_BN: false
  log_iter: 100
  with_test: false
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 30000
  save_name: MTSGait
  sync_BN: true
  total_iter: 180000
  sampler:
    batch_shuffle: true
    batch_size:
      - 32 # TripletSampler, batch_size[0] indicates Number of Identity
      - 4 #                 batch_size[1] indicates Samples sequqnce for each Identity
    frames_num_fixed: 30 # fixed frames number for training
    frames_num_max: 50 # max frames number for unfixed training
    frames_num_min: 25 # min frames number for unfixed traing
    sample_type: fixed_ordered # fixed control input frames number, unordered for controlling order of input tensor; Other options: unfixed_ordered or all_ordered
    noncyclic: true
    type: TripletSampler
  transform:
    - type: BaseParsingCuttingTransform
